settings:
    activities:
        ADMIN_PRODUCTS:
            - ADMIN:
                - controller@qualifier
        ADMIN_DASHBOARD:
            - ADMIN
    redirects:
        ADMIN_PRODUCTS: /admin/login
        ADMIN_DASHBOARD: /admin/login
