route:
    GET:
        /:                              website@homePage
        /page/{name}:                   website@page
        /product:                       ecommerce@productPage
        /cart:                          ecommerce@cartPage
        /checkout:                      ecommerce@checkoutPage
        /receipt:                       ecommerce@receiptPage
        /admin:                         admin@homePage
        /admin/login:                   admin@loginPage
        /admin/register:                admin@registerPage
        /admin/logout:                  admin@logout
        /admin/products:                ecommerce@adminProducts
        /admin/product/{id}:            ecommerce@adminProduct
    POST:
        /api/admin/login:               admin@login
        /api/admin/register:            admin@register
        /api/cart/add:                  ecommerce@cartAdd
        /api/cart/remove:               ecommerce@cartRemove
        /api/cart/quantity:             ecommerce@cartQuantity
        /api/order/submit:              ecommerce@orderSubmit
        /api/admin/product/sort:        ecommerce@adminProductSort
        /api/admin/product/add:         ecommerce@adminProductAdd
        /api/admin/product/edit:        ecommerce@adminProductEdit
